#!/usr/bin/env bash
#a Bash script that transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

export SCP_OPTS="-o StrictHostKeyChecking=no"

scp -i "$ssh_key_path" $SCP_OPTS "$file_path" "$username@$server_ip":~/

if [ $? -eq 0 ]; then
	echo "File transferred to $username@$server_ip:~/"
else
	echo "Error: File transfer failed"
fi
