#!/usr/bin/env bash
#Installing a server, generating and serving HTML pages

sudo apt-get update
sudo apt-get install -y nginx

echo "<html>
  <head>
    <title> Welcome </title>
  </head>
  <body>
    <p>Holberton School</p>
  </body>
</html>" | sudo tee /var/ww/html/index.html

echo "server {
    listen 80;
    server_name _;

    location / {
	root /var/www/html;
	indexindex.html;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo /etc/init.d/nginx restart
