#!/usr/bin/env bash
# installing and config nginx

sudo apt-get update
sudo apt-get install -y nginx

#write Holberton school in index.html
sudo mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Holberton School" | sudo tee /etc/nginx/html/index.html > /dev/null

sudo sed -i 's/^\(listen [::]:80\)/# \1/' /etc/nginx/sites-available/default
sudo service nginx restart
# Test the nginx setup with curl

response=$(curl -s http://localhost)
expected="Holberton School"

# Check if the response contains the expected string
if [[ "$response" == *"$expected"* ]]; then
    echo "Nginx installation and configuration successful!"
else
    echo "Error: Nginx configuration did not return the expected string."
fi
